_security_logout:
    resource: security.route_loader.logout
    type: service

security:
    firewalls:
        main:
            form_login:
                username_parameter: email
                password_parameter: password
